### ISSUE TITLE
TypeError: Cannot read property 'onReceive' of undefined

### ISSUE THREAD

**Issue by jawil003** [reZach/i18next-electron-fs-backend#9]
I got an error I don't understand? Is this because I mis some config? Cannot find something I missed.

```
TypeError: Cannot read property 'onReceive' of undefined
    at a.setupIpcBindings (/Users/jannik/Documents/CodeTracker/node_modules/i18next-electron-fs-backend/lib/index.js:1:4314)
    at a.init (/Users/jannik/Documents/CodeTracker/node_modules/i18next-electron-fs-backend/lib/index.js:1:4177)
    at new a (/Users/jannik/Documents/CodeTracker/node_modules/i18next-electron-fs-backend/lib/index.js:1:3386)
    at createClassOnDemand (/Users/jannik/Documents/CodeTracker/node_modules/i18next/dist/cjs/i18next.js:1925:57)
    at I18n.init (/Users/jannik/Documents/CodeTracker/node_modules/i18next/dist/cjs/i18next.js:1951:44)
    at Module../localization/i18n.mainconfig.ts (/Users/jannik/Documents/CodeTracker/app/background.js:169:120)
    at __webpack_require__ (/Users/jannik/Documents/CodeTracker/app/background.js:27:30)
    at Module../main/background.ts (/Users/jannik/Documents/CodeTracker/app/background.js:272:87)
    at __webpack_require__ (/Users/jannik/Documents/CodeTracker/app/background.js:27:30)
    at /Users/jannik/Documents/CodeTracker/app/background.js:139:18
```

Should I porvide an example for you?

**Comment by reZach** [comment]
@jawil003 I believe this is happening because you are missing code in your **preload.js** file. (Sample taken from [home page](https://github.com/reZach/i18next-electron-fs-backend))

```js
const {
    contextBridge,
    ipcRenderer
} = require("electron");
const backend = require("i18next-electron-fs-backend");

contextBridge.exposeInMainWorld(
    "api", {
        i18nextElectronBackend: backend.preloadBindings(ipcRenderer) // < this needs to be here
    }
);
```

I've [pushed a new release](https://github.com/reZach/i18next-electron-fs-backend/releases/tag/v1.3.7) with additional logging that can help point out this error to others in the future. Can you let me know if this file is set up for you?

**Comment by reZach** [comment]
@jawil003 I assume your error is fixed, please let me know if otherwise.
